before_script:
    - apt-get update -qq
    - apt-get install -qq git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      
deploy_production:
    type: deploy
    environment:
        name: production
        url: vikione.exchange
    script:
        - ssh thinh@34.123.12.16 "cd var/www/ && git checkout master && git pull origin master && exit"
    only:
        - master